language: python
git:
  depth: 3
branches:
  only:
  - main
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python3 main.py
env:
  matrix:
  - UUU=kkk
  global:
    secure: qPE7u6C9iVHRnHfscK7nERRGI+BBFnVNJPW17/5UHROu4bUMwYi1x5NnI6Dr1252YisOuUb7OZCz5gqrwEvXEbmUJiWnwdI9F8UbXIhcqP0xz/4c8Ao7eoCyzOa1wDqJKj/VaEDukGz88bHe3DMPflc8NA3f7KN6ijDLmUPaDQIF8zZfzptzA3WaN9hSklypdarENUkrJtxaptPtCrebSRH1TLi9MzRnSNyRe8ZDjurDHa8tLepKnlURN5tIq802/xPh2MFtUs5s3swjjh9IwgfOfRILGx0cSCBjspYAoWpiZIl9SC7j901ozx8S6xkmn6uMuxO5+6TJME5aznmLrQWaQGDhu+nEOCIC/BEQtAJJURZYzBR4pFzr0ET1NFdPnA8KY09oOgW41ijuBTubO7SJsOUfa+b1E2VCO6GVqazI7dCILdsIdBYdK2UYMRqsZqFS0XT/95fA1ufrmD++WUUr2jOUWKTZvb7JAKyDCe2WacIXGctap1z4XmmqvVvVFIglO5hmV+Vipj+3al3t3qpneA49odUzddoRF37Km4fD3gvx7Nxwmi+iu+FJOnWwZa+UVbWLDsL8DaV2JoMozI+oYM3ine1T6Jr2s8n7SrCspDrGKXGxOzCdqPmexiQCwYK64MQzdUMkwYj++RiBBnerTXbs8HHzjbPeEYDCkNE=
